config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :index, :new, :edit, :create] 
  resources :dashboard, only: [:index]
  resources :people do
    resources :hotline
  end
  
  get "hotline/_hotlines_edit" => 'hotline#_hotlines_edit', :as => :edit_hotline
  get "hotline/_hotlines_add" => 'hotline#_hotlines_add', :as => :add_hotline
  
  post 'dashboard/search'
  get '/person/:id', to: 'person#show'
  get 'welcome/index'
  get 'welcome/about'
  
  root to: 'welcome#index'

  
  get '*path' => redirect('/')
end

app/models/hotline.rb
class Hotline
  include Mongoid::Document
  #embedded_in :person
  
  field :person_id, type: Integer
  field :city, type: String
  field :zip, type: String
  field :client, type: Boolean
end

app/models/person.rb
class Person < ActiveRecord::Base
  def self.search(first_name, last_name)
    where("first_name ilike ?", "%#{first_name}%").where("last_name ilike ?", "%#{last_name}%")
  end
  
  def self.searchdob(first_name, last_name, dob)
    where("first_name ilike ?", "%#{first_name}%").where("last_name ilike ?", "%#{last_name}%").where("dob = ?", "%#{dob}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :lockable
  
  def admin?
    role == 'admin'
  end
  
  def genuser?
    role == 'genuser'
  end
 
  def viewonly?
    role == 'viewonly'
  end
  
  #default_scope { order(first_name: :asc, last_name: :asc) }
  default_scope { order('LOWER(first_name)', 'LOWER(last_name)') }
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  def show
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: "Not Authorized"
  end
  
  rescue_from Pundit::NotDefinedError do |exception|
    redirect_to root_url, alert: "Not Authorized"
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    authorize current_user
  end
  
  def show
    authorize current_user
  end
  
  def search
    if params[:dob] == ""
      @people = Person.search(params[:first_name], params[:last_name]).order("first_name ASC")
      render 'index'
    else
      @people = Person.searchdob(params[:first_name], params[:last_name], params[:dob]).order("first_name ASC")
      render 'index'
    end
  end
end

app/controllers/hotline_controller.rb
class HotlineController < ApplicationController
  
  def hotlines_edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = Person.new
    authorize current_user
  end

  def create
    @person = Person.new(person_params)
    authorize current_user
    if @person.save
      redirect_to person_path(@person), notice: "Person was added successfully."
    else
      flash[:error] = "Error creating person. Please try again."
      render :new
    end
  end

  def update
    @person = Person.find(params[:id])
      authorize current_user
     if @person.update_attributes(person_params)
       redirect_to person_path, notice: "Person was updated successfully."
     else
       flash[:error] = "Error saving person. Please try again."
       render :edit
     end
  end

  def edit
    @person = Person.find(params[:id])
    @person.save
    authorize current_user
  end

  def destroy
    @person = Person.find(params[:id])
 
    if @person.destroy
      #flash[:notice] = "Person was deleted successfully."
      redirect_to dashboard_index_path, notice: "Person was deleted successfully."
     else
      flash[:error] = "There was an error deleting the person. Please try again."
     end
  end

  def show
    @person = Person.find(params[:id])
    #@hotlines = Hotline.where(person_id: @person.id)
    
    respond_to do |format|              
      format.html
      format.js
    end        
  end
  
  private

  def person_params
    params.require(:person).permit(:first_name, :middle_name, :last_name, :dob, :address_line_1, :address_line_2, :city, :state, :zip, :primary_phone, :secondary, :email, :ssn)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  def after_sign_up_path_for(resource)
    administration_show_path # Or :prefix_to_your_route
  end
  
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :active, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :active, :email, :password, :password_confirmation, :current_password)
  end
  

  
  #def sign_up(resource_name, resource)
    #true
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    authorize current_user
  end

  def create
    @user = User.new(user_params)
    authorize current_user
    if @user.save
      redirect_to users_path, notice: "User was saved successfully."
    else
      flash[:error] = "Error creating user. Please try again."
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    authorize current_user
    if (user_params["password"] == "" && user_params["active"] == "true")
      @user.locked_at = nil
      @user.failed_attempts = 0
      @user.update_attributes(user_params.except(:password, :password_confirmation))
      redirect_to edit_user_path(@user), notice: "User was saved successfully."
    elsif (user_params["password"] == "" && user_params["active"] == "false")
      @user.locked_at = Time.now
      @user.failed_attempts  = 10
      @user.update_attributes(user_params.except(:password, :password_confirmation))
      redirect_to edit_user_path(@user), notice: "User was saved successfully."
    elsif (user_params["password"] != "" && user_params["active"] == "true")
      @user.locked_at = nil
      @user.failed_attempts  = 0
      @user.update_attributes(user_params)
      redirect_to edit_user_path(@user), notice: "User was saved successfully."
    elsif (user_params["password"] != "" && user_params["active"] == "false")
      @user.locked_at = Time.now
      @user.failed_attempts = 10
      @user.update_attributes(user_params)
      redirect_to edit_user_path(@user), notice: "User was saved successfully."
    else
      flash[:error] = "Error saving user. Please try again."
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
    @user.save
    authorize current_user
  end

  def index
    @users_active = User.where(active: true)
    @users_inactive = User.where(active: false)
    authorize current_user
  end
  
  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :active, :email, :password, :password_confirmation, :role)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hotline_helper.rb
module HotlineHelper
  
  def hotline_show
    @person = Person.find(params[:id])
    @hotlines = Hotline.where(person_id: @person.id)
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/administration/show.html.erb
<%= render partial: 'devise/registrations/form' %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<br>
<%= render partial: 'people/search' %>

app/views/hotline/_hotlines_add.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>

app/views/hotline/_hotlines_add.js.erb
$("#modal-window").html("<%= escape_javascript(render 'hotline/hotlines_add') %>");

app/views/hotline/_hotlines_edit.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>

app/views/hotline/_hotlines_edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'hotline/hotlines_edit') %>");

app/views/hotline/_hotlines_show.html.erb
<h3>History</h3>

<br>
<% hotlines.each do |h| %>
  <%= h.city %><br>
<% end %>

app/views/hotline/_modal.html.erb
<div class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-heading">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary">Add to Cart</a>
  </div>
</div>

app/views/hotline/create.html.erb
<h1>Hotline#create</h1>
<p>Find me in app/views/hotline/create.html.erb</p>

app/views/hotline/destroy.html.erb
<h1>Hotline#destroy</h1>
<p>Find me in app/views/hotline/destroy.html.erb</p>

app/views/hotline/edit.html.erb
<h1>Hotline#edit</h1>
<p>Find me in app/views/hotline/edit.html.erb</p>

app/views/hotline/index.html.erb
<h1>Hotline#index</h1>
<p>Find me in app/views/hotline/index.html.erb</p>

app/views/hotline/new.html.erb
<h1>Hotline#new</h1>
<p>Find me in app/views/hotline/new.html.erb</p>

app/views/hotline/show.html.erb
<h1>Hotline#show</h1>
<p>Find me in app/views/hotline/show.html.erb</p>

app/views/hotline/show.js.erb
$modal = $('.modal'),
$modalBody = $('.modal .modal-body'),
$modalHeading = $('.modal .modal-heading');
$modalHeading.html("TESTING PRISM");
$modalBody.html("TESTING PRISM");
$modal.modal();

app/views/hotline/update.html.erb
<h1>Hotline#update</h1>
<p>Find me in app/views/hotline/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prism</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", welcome_index_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
    <% if current_user %><li><%= link_to "Dashboard", dashboard_index_path %></li><% end %>
    <% if current_user %><li><%= link_to "My Profile", edit_user_path(current_user) %></li><% end %>
    <% if current_user && current_user.admin? %><li><%= link_to "User Admin", users_path %></li><% end %>
    
    <li class="pull-right">
      <% if current_user %>
        <%= link_to "Logged in as: "+current_user.last_name+", "+current_user.first_name+" Last login: "+current_user.last_sign_in_at.to_s(:long) +" - Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
      <% end %>
    </li>
    
  </ul>
  <br>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  <%= yield %>
</div>
</body>
<br>
</html>

app/views/people/_hotlines_show.html.erb
<h3>History</h3>
<br>
<% @hotlines.each do |h| %>
  <%= h.city %><br>
<% end %>

app/views/people/_search.html.erb
<h4>Person Search: </h4>
<%= form_tag({:controller => "dashboard", :action => "search"}, :method => "post", id: "search-form") do %>
  <%= text_field_tag :first_name, params[:first_name], placeholder: "First Name" %>
  <%= text_field_tag :last_name, params[:last_name], placeholder: "Last Name" %>
  <%= date_field_tag :dob, params[:dob] %>
  <%= submit_tag "Search", class: 'btn btn-sm btn-success' %>
  <%= link_to "Add New Person", new_person_path, class: 'btn btn-sm btn-success' %>
<% end %>
<br>
<% if @people.present? %>       
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Last Name</th>
        <th>DOB</th>
        <th>Address</th>
        <th></th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Primary Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @people.each do |p| %>
      <tr>
        <td class="col-md-1"><%= link_to p.first_name, person_path(p) %></td>
        <td class="col-md-1"><%= link_to p.middle_name, person_path(p) %></td>
        <td class="col-md-1"><%= link_to p.last_name, person_path(p) %></td>
        <td class="col-md-1"><% if p.dob.nil? %><% "" %><% else %><%= link_to p.dob.try(:strftime, '%m/%d/%Y'), person_path(p) %><% end %></td>
        <td class="col-md-2"><%= link_to p.address_line_1, person_path(p) %></td>
        <td class="col-md-1"><%= link_to p.address_line_2, person_path(p) %></td>
        <td class="col-md-1"><%= link_to p.city, person_path(p) %></td>
        <td class="col-md-1"><%= link_to p.state, person_path(p) %></td>
        <td class="col-md-1"><%= link_to p.zip, person_path(p) %></td>
        <td class="col-md-2"><%= link_to p.primary_phone, person_path(p) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% elsif @people.nil? %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>People#destroy</h1>
<p>Find me in app/views/people/destroy.html.erb</p>

app/views/people/edit.html.erb
<h4>Add new person</h4>

<%= form_for @person do |f| %>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">Name</label>
      <div class="col-sm-3">
        <%= f.text_field :first_name, autofocus: true, class: 'form-control input-sm', placeholder: "First name" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-2">
        <%= f.text_field :middle_name, class: 'form-control input-sm', placeholder: "Middle name" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-3">
        <%= f.text_field :last_name, class: 'form-control input-sm', placeholder: "Last name" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">DOB</label>
      <div class="col-sm-2">
        <%= f.date_field :dob, class: 'form-control input-sm', placeholder: "mm/dd/yyy" %>
      </div>
      <label class="col-sm-1 rt-label" for="textinput"></label>
      <label class="col-sm-1 rt-label" for="textinput">SSN</label>
      <div class="col-sm-2">
        <%= f.text_field :ssn, class: 'form-control input-sm', placeholder: "###-##-####" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">Address</label>
      <div class="col-sm-3">
        <%= f.text_field :address_line_1, class: 'form-control input-sm', placeholder: "Address line 1" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-3">
        <%= f.text_field :address_line_2, class: 'form-control input-sm', placeholder: "Address line 2" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-3">
        <%= f.text_field :city, autofocus: true, class: 'form-control input-sm', placeholder: "City" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-1">
        <%= f.text_field :state, class: 'form-control input-sm', placeholder: "State" %>
      </div>
      <label class="col-sm-2" for="textinput"></label>
      <div class="col-sm-2">
        <%= f.text_field :zip, class: 'form-control input-sm', placeholder: "Zip" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">Phone</label>
      <div class="col-sm-2">
        <%= f.text_field :primary_phone, class: 'form-control input-sm', placeholder: "Primary phone" %>
      </div>
      <label class="col-sm-2" for="textinput"></label>
      <div class="col-sm-2">
        <%= f.text_field :secondary_phone, class: 'form-control input-sm', placeholder: "Secondary phone" %>
      </div>
    </div>
  </div>
<br>
  <div class="form-group">
    <label class="col-sm-1" for="textinput"></label>
    <%= f.submit "Save", class: 'btn btn-sm btn-success' %>
    <%= link_to "Delete", person_path, method: :delete, class: 'btn btn-danger btn-sm' %>
  </div>
<% end %>

app/views/people/index.html.erb
<h1>People#index</h1>
<p>Find me in app/views/people/index.html.erb</p>
<% if @people.present? %>
<% @people.each do |p| %>
  <%= p.first_name %> <%= p.last_name %><br>
<% end %>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/people/new.html.erb
<h4>Add new person</h4>

<%= form_for @person do |f| %>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">Name</label>
      <div class="col-sm-3">
        <%= f.text_field :first_name, autofocus: true, class: 'form-control input-sm', placeholder: "First name" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-2">
        <%= f.text_field :middle_name, class: 'form-control input-sm', placeholder: "Middle name" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-3">
        <%= f.text_field :last_name, class: 'form-control input-sm', placeholder: "Last name" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">DOB</label>
      <div class="col-sm-2">
        <%= f.date_field :dob, class: 'form-control input-sm', placeholder: "mm/dd/yyy" %>
      </div>
      <label class="col-sm-1 rt-label" for="textinput"></label>
      <label class="col-sm-1 rt-label" for="textinput">SSN</label>
      <div class="col-sm-2">
        <%= f.text_field :ssn, class: 'form-control input-sm', placeholder: "###-##-####" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">Address</label>
      <div class="col-sm-3">
        <%= f.text_field :address_line_1, class: 'form-control input-sm', placeholder: "Address line 1" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-3">
        <%= f.text_field :address_line_2, class: 'form-control input-sm', placeholder: "Address line 2" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-3">
        <%= f.text_field :city, autofocus: true, class: 'form-control input-sm', placeholder: "City" %>
      </div>
      <label class="col-sm-1" for="textinput"></label>
      <div class="col-sm-1">
        <%= f.text_field :state, class: 'form-control input-sm', placeholder: "State" %>
      </div>
      <label class="col-sm-2" for="textinput"></label>
      <div class="col-sm-2">
        <%= f.text_field :zip, class: 'form-control input-sm', placeholder: "Zip" %>
      </div>
    </div>
  </div>
  <div class="row top-buffer">
    <div class="form-group">
      <label class="col-sm-1 rt-label" for="textinput">Phone</label>
      <div class="col-sm-2">
        <%= f.text_field :primary_phone, class: 'form-control input-sm', placeholder: "Primary phone" %>
      </div>
      <label class="col-sm-2" for="textinput"></label>
      <div class="col-sm-2">
        <%= f.text_field :secondary_phone, class: 'form-control input-sm', placeholder: "Secondary phone" %>
      </div>
    </div>
  </div>
<br>
  <div class="form-group">
    <label class="col-sm-1" for="textinput"></label>
    <%= f.submit "Save", class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/people/show.html.erb
<h4>Client: <i><%= link_to "#{@person.last_name}, #{@person.first_name}", edit_person_path(@person) %></i> DOB: <i><% if @person.dob.nil? %><% "" %><% else %><%= link_to "#{@person.dob.try(:strftime, '%m/%d/%Y')}", edit_person_path(@person) %></i><% end %></h4>
<b>Address:</b><%= " #{@person.address_line_1} #{@person.address_line_2} #{@person.city}, #{@person.state} #{@person.zip}" %> <b>Primary Phone:</b> <%= " #{@person.primary_phone}" %>
<br>
<br>
<div class="row">
   <div class="tabbable tabs-left">
     <ul class="nav nav-tabs">
       <li class="active"><a href="#casemanagement" data-toggle="tab">Case Management</a></li>
       <li><a href="#shelter" data-toggle="tab">Shelter</a></li>
       <li><a href="#hotline" data-toggle="tab">Hotline</a></li>
     </ul>
     <div class="tab-content">
       <div class="tab-pane active" id="casemanagement">
         <%= "Case Management" %>
       </div>
       <div class="tab-pane" id="shelter">
         <%= "Shelter" %>
       </div>
       <div class="tab-pane" id="hotline">
         <%= link_to 'Add Hotline', add_hotline_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>
         <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
       </div>
     </div>
   </div>
</div>
<%= render "hotline/modal" %>

app/views/people/update.html.erb
<h1>People#update</h1>
<p>Find me in app/views/people/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h3>Edit User</h3>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
      <%= devise_error_messages! %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, autofocus: true, class: 'form-control', placeholder: "Enter first name" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control', placeholder: "Enter last name" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      </div>
      <% if current_user.admin? %>
      <div class="form-group">
        <%= f.label :role %> (Select One)<br>
        <%= f.radio_button :role, :genuser %> General User
        <%= f.radio_button :role, :viewonly %> View Only
        <%= f.radio_button :role, :admin %> Administrator
      </div>
      <div class="form-group">
        <%= f.label :status %><br>
        <%= f.check_box :active, {}, "true", "false" %> Active User
      </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>User Administration</h1>

<% if policy(User.new).create? %>
<%= link_to "Add New User", new_user_path, class: 'btn btn-success' %>
<% end %>

<br>
<br>

<h3>Active Users</h3>

<div class="container">           
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users_active.each do |user| %>
      <tr>
        <td class="col-md-2"><%= link_to user.first_name, edit_user_path(user) %></td>
        <td class="col-md-2"><%= link_to user.last_name, edit_user_path(user) %></td>
        <td class="col-md-4"><%= link_to user.email, edit_user_path(user) %></td>
        <td class="col-md-2"><%= link_to user.role, edit_user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h3>Inactive Users</h3>

<div class="container">           
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users_inactive.each do |user| %>
      <tr>
        <td class="col-md-2"><%= link_to user.first_name, edit_user_path(user) %></td>
        <td class="col-md-2"><%= link_to user.last_name, edit_user_path(user) %></td>
        <td class="col-md-4"><%= link_to user.email, edit_user_path(user) %></td>
        <td class="col-md-2"><%= link_to user.role, edit_user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>Prism by DataLumina LLC,</h1>
<p>Prism is a efforts to outcomes software designed to track clients, and bring your data to light easily.</p>
<p>For more information please contact:<br>
<br>
DataLumina LLC,<br>
www.datalumina.com</p>